# Generated by Django 4.0.6 on 2023-01-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(default='MEIPMPTR76HA24QE5HCMROFIJ7NL7O3W', max_length=32, verbose_name='secret'),
        ),
    ]
