# Generated by Django 4.0.6 on 2023-01-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.CharField(max_length=32, verbose_name='secret'),
        ),
    ]
