# Generated by Django 4.0.6 on 2023-05-03 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_confirmationemailcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 5, 19, 56, 958211), verbose_name='sub_end_date'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=False, verbose_name='subscribed'),
        ),
    ]
