# Generated by Django 4.0.6 on 2023-01-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='secret'),
        ),
    ]
