# Generated by Django 4.0.6 on 2023-05-03 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_sub_end_date_user_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='customer_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 19, 15, 2, 277722), verbose_name='sub_end_date'),
        ),
    ]
