# Generated by Django 4.0.6 on 2023-06-27 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_sub_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 6, 19, 0, 626578), verbose_name='sub_end_date'),
        ),
    ]
