# Generated by Django 4.0.6 on 2026-03-15 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_sub_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='user',
            name='revenuecat_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='customer_id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 5, 22, 36, 18320), verbose_name='sub_end_date'),
        ),
    ]
