# Generated by Django 4.0.6 on 2026-03-15 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_subscribed_user_revenuecat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 5, 22, 38, 665571), verbose_name='sub_end_date'),
        ),
    ]
