# Generated by Django 4.0.6 on 2026-03-15 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_sub_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_end_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 14, 7, 2, 21, 94957), verbose_name='sub_end_date'),
        ),
    ]
