# Generated by Django 4.0.6 on 2023-01-28 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedWorkoutGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('caption', models.CharField(max_length=250)),
                ('media_ids', models.CharField(default='[]', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('for_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75, unique=True)),
                ('code', models.CharField(max_length=12)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(max_length=100)),
                ('owned_by_class', models.BooleanField(default=True)),
                ('finished', models.BooleanField(default=False)),
                ('for_date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=250)),
                ('media_ids', models.CharField(default='[]', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_archived', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('owner_id', 'owned_by_class', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('scheme_type', models.IntegerField(default=0)),
                ('scheme_rounds', models.CharField(default='[]', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.workoutgroups')),
            ],
            options={
                'unique_together': {('group', 'title')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=3000)),
                ('media_ids', models.CharField(default='[]', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='gyms.workoutcategories')),
                ('primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workoutcategories_primary_set', to='gyms.workoutcategories')),
                ('secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workoutcategories_secondary_set', to='gyms.workoutcategories')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.IntegerField(blank=True, default=-1)),
                ('constant', models.BooleanField(blank=True, default=False)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.CharField(default='[0]', max_length=140)),
                ('duration', models.CharField(default='[0]', max_length=140)),
                ('duration_unit', models.IntegerField(default=0)),
                ('distance', models.CharField(default='[0]', max_length=140)),
                ('distance_unit', models.IntegerField(default=0)),
                ('weights', models.CharField(default='[]', max_length=400)),
                ('weight_unit', models.CharField(default='kg', max_length=2)),
                ('rest_duration', models.FloatField(default=0.0)),
                ('rest_duration_unit', models.IntegerField(default=0)),
                ('percent_of', models.CharField(default='', max_length=20)),
                ('order', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.workoutnames')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.workouts')),
            ],
        ),
        migrations.CreateModel(
            name='Gyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('owner_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('title', 'owner_id')},
            },
        ),
        migrations.CreateModel(
            name='GymClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('private', models.BooleanField(default=False)),
                ('desc', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gyms')),
            ],
            options={
                'unique_together': {('title', 'gym')},
            },
        ),
        migrations.CreateModel(
            name='CompletedWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=250)),
                ('scheme_type', models.IntegerField(default=0)),
                ('scheme_rounds', models.CharField(default='[]', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('completed_workout_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.completedworkoutgroups')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.workouts')),
            ],
            options={
                'unique_together': {('completed_workout_group', 'workout', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='CompletedWorkoutItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('ssid', models.IntegerField(blank=True, default=-1)),
                ('constant', models.BooleanField(blank=True, default=False)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.CharField(default='0', max_length=140)),
                ('duration', models.CharField(default='0', max_length=140)),
                ('duration_unit', models.IntegerField(default=0)),
                ('distance', models.CharField(default='0', max_length=140)),
                ('distance_unit', models.IntegerField(default=0)),
                ('weights', models.CharField(default='[]', max_length=400)),
                ('weight_unit', models.CharField(default='kg', max_length=2)),
                ('rest_duration', models.FloatField(default=0.0)),
                ('rest_duration_unit', models.IntegerField(default=0)),
                ('percent_of', models.CharField(default='1RM', max_length=20)),
                ('order', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('completed_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.completedworkouts')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.workoutnames')),
            ],
        ),
        migrations.AddField(
            model_name='completedworkoutgroups',
            name='workout_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gyms.workoutgroups'),
        ),
        migrations.CreateModel(
            name='BodyMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('bodyweight', models.FloatField(default=0.0)),
                ('bodyweight_unit', models.CharField(default='kg', max_length=2)),
                ('bodyfat', models.FloatField(default=0.0)),
                ('armms', models.FloatField(default=0.0)),
                ('calves', models.FloatField(default=0.0)),
                ('neck', models.FloatField(default=0.0)),
                ('thighs', models.FloatField(default=0.0)),
                ('chest', models.FloatField(default=0.0)),
                ('waist', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LikedWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.workouts')),
            ],
            options={
                'unique_together': {('user_id', 'workout')},
            },
        ),
        migrations.CreateModel(
            name='GymFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gyms')),
            ],
            options={
                'unique_together': {('user_id', 'gym')},
            },
        ),
        migrations.CreateModel(
            name='GymClassFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gymclasses')),
            ],
            options={
                'unique_together': {('user_id', 'gym_class')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='completedworkoutgroups',
            unique_together={('workout_group', 'user_id')},
        ),
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gymclasses')),
            ],
            options={
                'unique_together': {('user_id', 'gym_class')},
            },
        ),
        migrations.CreateModel(
            name='ClassMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('gym_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.gymclasses')),
            ],
            options={
                'unique_together': {('user_id', 'gym_class')},
            },
        ),
    ]
