# Generated by Django 4.0.6 on 2023-01-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutitems',
            name='pause_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
