# Generated by Django 4.0.6 on 2022-12-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutitems',
            name='constant',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
