# Generated by Django 4.0.6 on 2023-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_workoutitems_pause_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedworkoutitems',
            name='pause_duration',
            field=models.FloatField(default=0.0),
        ),
    ]
