# Generated by Django 4.0.6 on 2023-04-09 21:46

from django.db import migrations


class Migration(migrations.Migration):
    sql = """
            CREATE TRIGGER check_count_gyms
                BEFORE INSERT ON gyms_gyms
                FOR EACH ROW
                WHEN (NEW.owner_id IS NOT NULL)
                EXECUTE FUNCTION check_gym_count('3', 'gyms_gyms');
    """
    dependencies = [
        ('gyms', '0004_tigger_limit_gyms'),
    ]

    operations = [
        migrations.RunSQL(sql),
    ]
