# Generated by Django 4.0.6 on 2023-04-10 01:25

from django.db import migrations


class Migration(migrations.Migration):
    sql = """
        CREATE OR REPLACE FUNCTION check_gymclasses_count()
        RETURNS TRIGGER  AS $$
        DECLARE
            row_count INTEGER;
        BEGIN
            -- Check the count of rows with the given owner_id in the table
            -- ARGS (TG_ARGV): max_rows, table_name
            EXECUTE format('SELECT COUNT(*) FROM %s WHERE gym_id = %s', TG_ARGV[1], NEW.gym_id)
            INTO row_count;


            IF row_count >= TG_ARGV[0]::integer THEN
                RAISE EXCEPTION 'Too many rows found for Gym ID %s in table %s', NEW.gym_id, TG_ARGV[1];
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """
    dependencies = [
        ('gyms', '0005_tigger_limit_gyms_trigger'),
    ]

    operations = [
        migrations.RunSQL(sql),
    ]
