# Generated by Django 4.0.6 on 2023-04-12 01:55

from django.db import migrations


class Migration(migrations.Migration):
    sql = """
      CREATE TRIGGER check_count_workoutgroups
                BEFORE INSERT ON gyms_workoutgroups
                FOR EACH ROW
                WHEN (NEW.owner_id IS NOT NULL)
                EXECUTE FUNCTION check_workoutgroups_count('15', 'gyms_workoutgroups');
    """

    dependencies = [
        ('gyms', '0008_tigger_limit_workout_group_daily'),
    ]

    operations = [
         migrations.RunSQL(sql),
    ]
