# Generated by Django 4.0.6 on 2023-05-23 05:36

from django.db import migrations


class Migration(migrations.Migration):

    sql = """
      CREATE TRIGGER check_count_completedworkoutgroups
                BEFORE INSERT ON gyms_completedworkoutgroups
                FOR EACH ROW
                WHEN (NEW.user_id IS NOT NULL)
                EXECUTE FUNCTION check_completed_workoutgroups_count('1', 'gyms_completedworkoutgroups');
    """
    dependencies = [
        ('gyms', '0010_tigger_limit_completed_workoutgroup'),
    ]

    operations = [
        migrations.RunSQL(sql),
    ]
