# Generated by Django 4.0.6 on 2026-03-15 05:22

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0011_func_limit_completed_workoutgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedWorkoutDualItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('ssid', models.IntegerField(blank=True, default=-1)),
                ('constant', models.BooleanField(blank=True, default=False)),
                ('finished', models.BooleanField(default=False)),
                ('penalty', models.CharField(default='', max_length=140)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.CharField(default='[0]', max_length=140)),
                ('pause_duration', models.FloatField(default=0.0)),
                ('duration', models.CharField(default='[0]', max_length=140)),
                ('duration_unit', models.IntegerField(default=0)),
                ('distance', models.CharField(default='[0]', max_length=140)),
                ('distance_unit', models.IntegerField(default=0)),
                ('weights', models.CharField(default='[]', max_length=400)),
                ('weight_unit', models.CharField(default='kg', max_length=2)),
                ('rest_duration', models.FloatField(default=0.0)),
                ('rest_duration_unit', models.IntegerField(default=0)),
                ('percent_of', models.CharField(default='', max_length=20)),
                ('order', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('r_sets', models.IntegerField(default=0)),
                ('r_reps', models.CharField(default='[0]', max_length=140)),
                ('r_pause_duration', models.FloatField(default=0.0)),
                ('r_duration', models.CharField(default='[0]', max_length=140)),
                ('r_duration_unit', models.IntegerField(default=0)),
                ('r_distance', models.CharField(default='[0]', max_length=140)),
                ('r_distance_unit', models.IntegerField(default=0)),
                ('r_weights', models.CharField(default='[]', max_length=400)),
                ('r_weight_unit', models.CharField(default='kg', max_length=2)),
                ('r_rest_duration', models.FloatField(default=0.0)),
                ('r_rest_duration_unit', models.IntegerField(default=0)),
                ('r_percent_of', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TokenQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('remaining_tokens', models.PositiveIntegerField(default=1000000)),
                ('reset_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkoutMax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('max_value', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkoutMaxHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200)),
                ('max_value', models.FloatField()),
                ('unit', models.CharField(default='kg', max_length=10)),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDualItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.IntegerField(blank=True, default=-1)),
                ('constant', models.BooleanField(blank=True, default=False)),
                ('finished', models.BooleanField(default=False)),
                ('penalty', models.CharField(default='', max_length=140)),
                ('sets', models.IntegerField(default=0)),
                ('reps', models.CharField(default='[0]', max_length=140)),
                ('pause_duration', models.FloatField(default=0.0)),
                ('duration', models.CharField(default='[0]', max_length=140)),
                ('duration_unit', models.IntegerField(default=0)),
                ('distance', models.CharField(default='[0]', max_length=140)),
                ('distance_unit', models.IntegerField(default=0)),
                ('weights', models.CharField(default='[]', max_length=400)),
                ('weight_unit', models.CharField(default='kg', max_length=2)),
                ('rest_duration', models.FloatField(default=0.0)),
                ('rest_duration_unit', models.IntegerField(default=0)),
                ('percent_of', models.CharField(default='', max_length=20)),
                ('order', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('r_sets', models.IntegerField(default=0)),
                ('r_reps', models.CharField(default='[0]', max_length=140)),
                ('r_pause_duration', models.FloatField(default=0.0)),
                ('r_duration', models.CharField(default='[0]', max_length=140)),
                ('r_duration_unit', models.IntegerField(default=0)),
                ('r_distance', models.CharField(default='[0]', max_length=140)),
                ('r_distance_unit', models.IntegerField(default=0)),
                ('r_weights', models.CharField(default='[]', max_length=400)),
                ('r_weight_unit', models.CharField(default='kg', max_length=2)),
                ('r_rest_duration', models.FloatField(default=0.0)),
                ('r_rest_duration_unit', models.IntegerField(default=0)),
                ('r_percent_of', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(default=dict)),
                ('items', models.JSONField(default=dict)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='workoutgroups',
            unique_together={('owner_id', 'owned_by_class', 'title', 'for_date')},
        ),
        migrations.AddField(
            model_name='completedworkouts',
            name='instruction',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='workoutgroups',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutgroups',
            name='template_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutgroups',
            name='template_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutgroups',
            name='template_num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workouts',
            name='instruction',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='completedworkoutgroups',
            name='caption',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='completedworkoutgroups',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='completedworkouts',
            name='desc',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='workoutgroups',
            name='caption',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='desc',
            field=models.CharField(max_length=280),
        ),
        migrations.AddIndex(
            model_name='workoutgroups',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='workoutgroup_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddField(
            model_name='workoutstats',
            name='workout',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='gyms.workouts'),
        ),
        migrations.AddField(
            model_name='workoutdualitems',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.workoutnames'),
        ),
        migrations.AddField(
            model_name='workoutdualitems',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.workouts'),
        ),
        migrations.AddField(
            model_name='userworkoutmaxhistory',
            name='workout_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_history', to='gyms.workoutnames'),
        ),
        migrations.AddField(
            model_name='userworkoutmax',
            name='workout_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_maxes', to='gyms.workoutnames'),
        ),
        migrations.AddField(
            model_name='completedworkoutdualitems',
            name='completed_workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.completedworkouts'),
        ),
        migrations.AddField(
            model_name='completedworkoutdualitems',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gyms.workoutnames'),
        ),
        migrations.AlterUniqueTogether(
            name='userworkoutmax',
            unique_together={('user_id', 'workout_name')},
        ),
    ]
