# Generated by Django 4.0.6 on 2026-03-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0012_completedworkoutdualitems_tokenquota_userworkoutmax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('package_id', models.CharField(max_length=50)),
                ('tokens_added', models.PositiveIntegerField()),
                ('price_paid_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('method', models.CharField(choices=[('mock', 'Mock (dev/promo)'), ('stripe', 'Stripe'), ('apple', 'Apple IAP'), ('google', 'Google Play')], default='mock', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tokenquota',
            name='total_tokens_used',
            field=models.BigIntegerField(default=0),
        ),
    ]
